// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTemUAGQQapsh4SdJX_Y8pkOBBMOCbGGo',
    appId: '1:40076882520:web:07e8d1c9782f64b3d9902d',
    messagingSenderId: '40076882520',
    projectId: 'slate-flutter-project',
    authDomain: 'slate-flutter-project.firebaseapp.com',
    storageBucket: 'slate-flutter-project.firebasestorage.app',
    measurementId: 'G-L5FD6NJQQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfqwZEWXIpmFZG5ymE2z3chtEEUvtjxKY',
    appId: '1:40076882520:android:1a9ba1d7edd07cc5d9902d',
    messagingSenderId: '40076882520',
    projectId: 'slate-flutter-project',
    storageBucket: 'slate-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJkzjhC18TRLuo43ZJFA_LrgZl3HUOJY',
    appId: '1:40076882520:ios:32afc66ced705a90d9902d',
    messagingSenderId: '40076882520',
    projectId: 'slate-flutter-project',
    storageBucket: 'slate-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.slate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJkzjhC18TRLuo43ZJFA_LrgZl3HUOJY',
    appId: '1:40076882520:ios:32afc66ced705a90d9902d',
    messagingSenderId: '40076882520',
    projectId: 'slate-flutter-project',
    storageBucket: 'slate-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.slate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTemUAGQQapsh4SdJX_Y8pkOBBMOCbGGo',
    appId: '1:40076882520:web:156959f879db224ad9902d',
    messagingSenderId: '40076882520',
    projectId: 'slate-flutter-project',
    authDomain: 'slate-flutter-project.firebaseapp.com',
    storageBucket: 'slate-flutter-project.firebasestorage.app',
    measurementId: 'G-FXZ90L012Q',
  );

}